# ----
# Site

title: Support Beit Eshel
url: "http://beitesheldonate.org/"
baseurl: 
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: The Home of Beit Eshel ministries.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Cause Template
  links:
    - https://github.com/CloudCannon/cause-jekyll-template

# -----
# Build

collections:
  staff_members:
    _hide_content: true
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
  -
    scope:
      path: ""
    values:
      layout: "default"

donation_embed: '<script src="https://donorbox.org/widget.js" type="text/javascript"></script><iframe src="https://donorbox.org/embed/help-fund-beit-eshel" height="685px" width="100%" style="max-width:500px; min-width:310px; max-height:none!important" seamless="seamless" name="donorbox" frameborder="0" scrolling="no" allowpaymentrequest ></iframe>'
newsletter_action: "https://website.us17.list-manage.com/subscribe/post?u=6684e49c7e897f24502c1ce42&amp;id=96cad527d6" 
     



gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
